(function(){var g=void 0,h=true,i=null,j=false,k,l=this;function m(a,b){function c(){}c.prototype=b.prototype;a.Q=b.prototype;a.prototype=new c;a.prototype.constructor=a};var aa=/[?&]__cb_debug=([^&]+)/i,ba={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},ca={scroll:2E4,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},da=/:\/\/static2\.chartbeat.com\/js\/chartbeat(_[a-z]+)?\.js$/;function ea(a,b){var c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}function fa(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function ga(a,b){var c="",d=ha(encodeURIComponent(a));d.splice(b||5,d.length);p(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function ha(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,n=3285377520,o=[],q,w,z,M,N,Z=Math.ceil((a.length/4+2)/16),W=[Z],A=0,x;A<Z;A++){W[A]=[];for(q=0;q<16;q++)W[A][q]=a.charCodeAt(A*64+q*4)<<24|a.charCodeAt(A*64+q*4+1)<<16|a.charCodeAt(A*64+q*4+2)<<8|a.charCodeAt(A*64+q*4+3)}A=(a.length-1)*8;a=Z-1;W[a][14]=Math.floor(A/Math.pow(2,32));W[a][15]=A&4294967295;for(A=0;A<Z;A++){for(x=0;x<16;x++)o[x]=W[A][x];
for(x=16;x<80;x++)o[x]=(o[x-3]^o[x-8]^o[x-14]^o[x-16])<<1|(o[x-3]^o[x-8]^o[x-14]^o[x-16])>>>31;a=c;q=d;w=e;z=f;M=n;for(x=0;x<80;x++)N=Math.floor(x/20),N=(a<<5|a>>>27)+(N==0?q&w^~q&z:N==1?q^w^z:N==2?q&w^q&z^w&z:q^w^z)+M+b[N]+o[x]&4294967295,M=z,z=w,w=q<<30|q>>>2,q=a,a=N;c=c+a&4294967295;d=d+q&4294967295;e=e+w&4294967295;f=f+z&4294967295;n=n+M&4294967295}return[c,d,e,f,n]}
function ia(a){var b=l.navigator,c=l.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];p(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=l.performance;d=d.concat([b&&b.now?b.now():"",document.title,l.location.href,r(),fa()]);return d.concat(a||[]).join()}function s(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}
function t(a){return typeof a!=="undefined"}function u(a){return a.replace(/^www\./,"")}function v(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function ja(a,b){var c=l;c.removeEventListener?c.removeEventListener(a,b,j):c.detachEvent&&c.detachEvent("on"+a,b)}function y(a){return typeof a==="number"}function B(a){return typeof a==="string"}function ka(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}
function r(){return(new Date).getTime()}function la(a){return encodeURIComponent(a)}function C(a){return!!a&&a.constructor===Object}function ma(a,b){if(!C(a)||!C(b))return a===b;var c=0,d=h;p(a,function(a,e){c++;return d=a===b[e]});if(!d)return j;var e=0;p(b,function(){e++});return c===e}function p(a,b){if(C(a)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===j)break}}
function na(a,b){var c=[];p(a,function(a,e){var f=b(a,e);c.push(f)});return c}function oa(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}function pa(a){if(C(a)===j)return"";var b=[];p(a,function(a,d){b.push(encodeURIComponent(d)+"::"+encodeURIComponent(a))});return b.join("&")}function qa(a){B(a)||(a="");var b={};p(a.split("&"),function(a){a=a.split("::");a.length===2&&(b[decodeURIComponent(a[0])]=decodeURIComponent(a[1]))});return b}
function ra(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,n=a.length;f<=n;f++)c[0][f]=f;for(var o,q,w,d=1;d<=e;d++)for(f=1;f<=n;f++)o=d-1,q=f-1,w=c[o][q],b.charAt(o)==a.charAt(q)?c[d][f]=w:(q=c[d][q]+1,o=c[o][f]+1,w+=2,c[d][f]=Math.min(q,o,w));return c[b.length][a.length]}var sa;function ta(){}var ua=l.setInterval,va=l.clearInterval,wa=l.setTimeout,D=l.clearTimeout;
function xa(a,b){var c={};p(b,function(b,e){c[b]=s(a[e],a)});return c}function ya(a){var b=[];if(!C(a))return b;for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}function za(){var a=t(l.XDomainRequest);return t(l.XMLHttpRequest)&&"withCredentials"in new l.XMLHttpRequest?new l.XMLHttpRequest:a?new l.XDomainRequest:i}
function Aa(a,b,c){var d=za();d===i?c(i):(Ba(function(){d.open("GET",a,h)}),d.onload=function(){d.responseText?b(d):c(d)},d.onerror=function(){c(d,"onerror")},d.timeout=1E3,d.ontimeout=function(){c(d,"timeout")},wa(function(){Ba(function(){d.send(i)})},0))}function Ba(a){try{a()}catch(b){}}function Ca(a){switch(a){case g:return"undefined";case "":return"empty";default:return a}};function Da(a,b,c){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");for(var d=[],b=c.getElementsByTagName(b),c=b.length;c--;)b[c].getAttribute(a)&&d.push(b[c]);return d}function E(a,b){var c=i;b&&(c=b.getAttribute(a));if(c===i){var d=Da(a,"*",b);d.length!==0&&(c=d[0].getAttribute(a))}return c}function Ea(a,b,c){return a===g?j:c===g&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?j:Ea(a.parentNode,b,c)}
function Fa(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=Da("data-cb-scroll-element"))&&c.length)return c[0][b];if(y(l[a]))return l[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}function Ga(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}function Ha(){return Ga("Height")}
function Ia(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function Ja(a,b,c){var d=a.ownerDocument.documentElement,e=0,f=t(c)?c+1:-1;B(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return i}function Ka(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function La(a){a=a||window.event;return!a?i:Ja(a.target||a.srcElement,Ka,10)}function Ma(a,b){var c=document.createElement(a);p(b,function(a,b){c.setAttribute(b,a)});return c}function Na(a){var b=t(g)?g:{};b.src=a;a=Ma("script",b);a.setAttribute("type","text/javascript");b=document.head||document.getElementsByTagName("head")[0];t(g)?g.appendChild(a):b&&b.appendChild(a)}
function Oa(){if(t(Pa))return Pa;var a;a:{a=document.getElementsByTagName("script");for(var b=a.length-1;b>-1;b--)if(da.test(a[b].getAttribute("src"))){a=a[b];break a}a=g}return Pa=t(a)}var Pa;function Qa(){this.T={};this.Bb=1}k=Qa.prototype;k.D=function(a,b,c){this.Bb++;this.T[a]=this.T[a]||{};this.T[a][this.Bb]=[b,c];return this.Bb};k.U=function(a){if(B(a))this.T[a]=g,delete this.T[a];else if(y(a)){var b=h;p(this.T,function(c){p(c,function(d,e){if(parseInt(e,10)===a)return c[e]=g,delete c[e],b=j});return b})}};k.J=function(a,b){if(this.T[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];p(this.T[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
k.addEventListener=function(a,b){var c=this.D(a,b);b._cbEventId=c};k.removeEventListener=function(a,b){this.T[a]&&this.T[a][b._cbEventId]&&this.T[a][b._cbEventId][0]===b&&this.U(b._cbEventId)};var F=new Qa,Ra="o",Sa={D:Ra,U:"f"},Ta="a";var G={};
G.q=function(){G.ob?G.Pa("pageload"):(G.kc=[{target:l,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:l,event:"resize"},{target:document.body,event:"mousedown"}],G.Ya=i,G.ja=i,G.nb={},G.mb={},G.Yb={},G.Za={},p(G.kc,function(a){var b=a.event;v(a.target,b,function(a){G.Pa.call(G,b,a)})}),F.D("f",function(){G.Pa("focus")}),G.Pa("pageload"),v(document.body,"click",function(a){(a=La(a))&&F.J("c",a)},h),v(document.body,"contextmenu",function(a){(a=La(a))&&
F.J("r",a)}),G.ob=h)};G.rc=function(){var a,b=G.Yb.keydown;if(b===g)return j;b=r()-b;return b<=(a||15E3)&&b>=0};G.za=function(a,b){var c=G.Za[a];if(!c)return"";var b=b||r(),d,e=0;p(c,function(a){d=Math.floor((b-a)/1E3);d>=0&&d<16&&(e|=1<<d)});c=("0000"+e.toString(16)).slice(-4);return c=="0000"?"":c};G.Zc=function(){G.Za={}};G.Hb=100;
G.Pa=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}G.dd(a);if(G.Ya===i)G.gc(a);else if(!G.ja||ba[G.ja]<ba[a]||ca[G.ja]<ca[a])G.ja=a};G.dd=function(a){var b=r();G.Yb[a]=b;var c=G.Za[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();G.Za[a]=c};G.gc=function(a){G.Ya=wa(G.vc,G.Hb);F.J(Ta);G.nb[a]!==i&&D(G.nb[a]);G.mb[a]!==i&&D(G.mb[a]);G.ec(a,G.nb,ba,"i");G.ec(a,G.mb,ca,"j")};
G.ec=function(a,b,c,d){b[a]=wa(function(){D(b[a]);delete b[a];var c=j;p(b,function(){c=h;return j});c||F.J(d)},c[a]+G.Hb)};G.vc=function(){D(G.Ya);G.Ya=i;if(G.ja)G.gc(G.ja),G.ja=i};var Ua,Va,Wa,Xa,Ya;(function(){var a,b;p(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof l.document[a]==="boolean")return b=c,j});b!==g&&(Xa=a,Ya=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),Wa=b+"visibilitychange")})();var Za=j;function $a(){Za=Ya&&l.document[Ya]==="prerender"?h:j}function ab(){Va=h;F.J("f")}function bb(){Va=j;F.J("b")}
function cb(a,b,c){l.addEventListener?l.addEventListener(a,c,j):l.document.attachEvent&&l.document.attachEvent(b,c)}function db(){var a=h;l.document.hasFocus&&(a=l.document.hasFocus());var b=j;Xa&&(b=l.document[Xa]);return a&&!b}function eb(){db()?ab():bb()}function fb(a){$a();if(Za){var b=j,c=function(){b||($a(),Za||(b=h,a(),l.window.setTimeout(function(){l.document.removeEventListener(Wa,c,j)},100)))};l.document.addEventListener(Wa,c,j)}else a()};function H(){this.k=l._sf_async_config||{};this.Nb=s(this.cc,this)}H.prototype.q=function(){this.wb=0};H.prototype.cc=function(){};H.prototype.Ha=function(a){Za||ea(a,this.Nb)};H.prototype.$=function(){this.Nb=i};function gb(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),p(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function hb(a,b){var c="",d=l.location.href.split("?");if(d.length){var d=gb(d[1]),e=b||a;d[e]&&(c=d[e])}return c}function ib(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function jb(a,b){var c=[];p(b,function(b){var e=a[b];t(e)&&(Object.prototype.toString.call(e)==="[object Array]"?p(e,function(a){c.push(b+"="+a)}):C(e)?p(e,function(a,b){c.push(b+"="+a)}):((e+"").length||b=="r")&&c.push(b+"="+e))});c.push("_");return c.join("&")}
function kb(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=l.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=ib(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?"/"+a:e.substr(0,f)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(ib(b.protocol,b.port)||b.port==="0")b.port="";return b}
function lb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash}function mb(){var a=0,b=(l.location.search||"").match(aa);b&&b[1]&&(a=parseInt(b[1],10));return a};function I(a,b,c){a[b]=a[b]||c}function nb(a,b){for(var c=l[a]||[];c.length;)b(c.shift());l[a]={push:b}}function ob(a){p(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=gb(b.src.split("?")[1]),I(a,"uid",b.uid),I(a,"domain",b.domain),j})}function pb(a,b){return a[b]?encodeURIComponent(a[b]):""}function qb(a){var b={};p(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};function rb(a){var b=a===document.documentElement?a.scrollHeight:a.offsetHeight,c=a.offsetWidth;if(b<=1||c<=1){var d=sb(a,["overflow","overflow-x","overflow-y"]);d.overflow==="hidden"||d["overflow-x"]==="hidden"||d["overflow-y"]==="hidden"||p(a.getElementsByTagName("iframe"),function(a){var d=a.offsetHeight,a=a.offsetWidth;if(d>1&&a>1)return b=d,c=a,j})}return{height:b,width:c}}function tb(a){a=rb(a);return a.height*a.width}
function ub(a){var b;"contains"in document.documentElement&&!document.documentElement.contains(a)?b=j:(b=rb(a),b=b.height>1&&b.width>1);if(!b)return j;b=sb(a,["visibility","display","overflow","opacity"]);if(b.visibility=="hidden"||b.display=="none"||b.opacity=="0")return j;if(b.overflow=="hidden"&&(a.offsetHeight==0||a.offsetWidth==0))return j;b=h;for(var c=a.parentElement;c&&b;){var d;if(c.scrollHeight===c.clientHeight&&c.scrollWidth===c.clientWidth)d=j;else{var e=sb(c,["overflow","overflow-x",
"overflow-y"]);d=e.overflow;var f=e["overflow-x"],e=e["overflow-y"];d=d==="auto"||d==="scroll"||f==="auto"||f==="scroll"||e==="auto"||e==="scroll"}d&&(b=vb(a,c));c=c.parentElement}return b&&vb(a,i)}function vb(a,b){var c,d;if(b){var e=rb(b);c=e.width;d=e.height}else c=Ga("Width"),d=Ha();var f=rb(a),e=f.height,f=f.width,n=wb(a,b),o=n.y,n=n.x;c=Math.min(n+f,f,c,c-n);d=Math.min(o+e,e,d,d-o);if(c<0||d<0)return j;e*=f;return c*d>=(e>=242500?0.3:0.5)*e}
function wb(a,b,c){var d=a.offsetLeft,e=a.offsetTop,f=xb(a);d+=f.x;e+=f.y;for(var n=j,o=c?0:Fa("X","Left",g),q=c?0:Fa("Y","Top",g),f=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===f)f=xb(a),d+=a.offsetLeft+f.x,e+=a.offsetTop+f.y,f=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(sb(a,["position"]).position==="fixed"){n=h;break}a=a.parentElement}c||(d-=b?b.scrollLeft:o,e-=b?b.scrollTop:q);n&&(d+=o,e+=q);return{x:d,y:e}}
function sb(a,b){var c={},d,e;l.getComputedStyle?d=l.getComputedStyle(a,i):a.currentStyle?e="currentStyle":a.style&&(e="style");p(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[e][b]});return c}var yb=/matrix(3d)?\((.*)\)/;function xb(a){var b={x:0,y:0},a=sb(a,["transform"]).transform;if(!B(a))return b;var c=a.match(yb);if(!c)return b;var a=c[2].split(", "),d;t(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};var J={},zb={fb:"g"};J.Ib={IDLE:0,mc:1,lc:2,Ka:3};J.oc={IDLE:0,mc:1,lc:2,Ka:3};J.X=0;J.Y=0;J.q=function(){if(!J.ob)F.D(Ta,J.Fc,J),F.D("i",J.Kc,J),F.D("f",J.Hc,J),F.D("b",J.Gc,J),F.D("j",J.Jc,J),J.ob=h};J.fb=function(){return J.X};J.Ec=function(){return J.Y};J.Fc=function(){J.X===1?J.ha(3):J.X===0&&J.ha(2);J.Y===1?J.ga(3):J.Y===0&&J.ga(2)};J.Kc=function(){J.X===3?J.ha(1):J.X===2&&J.ha(0)};J.Jc=function(){J.Y===3?J.ga(1):J.Y===2&&J.ga(0)};
J.Hc=function(){(J.X===0||J.X===2)&&J.ha(3);(J.Y===0||J.Y===2)&&J.ga(3)};J.Gc=function(){J.X===3?J.ha(2):J.X===1&&J.ha(0);J.Y===3?J.ga(2):J.Y===1&&J.ga(0)};J.ha=function(a){J.X=a;F.J("s",a)};J.ga=function(a){J.Y=a;F.J("x",a)};function Ab(a,b){this.ib=a||g;this.Fa=b||g;this.ea=this.M=0;this.Tb=s(this.Pc,this);this.zb=this.Z=i}k=Ab.prototype;k.q=function(){this.ea=this.M=0;this.Z=i;this.zb=F.D("s",this.Aa,this);this.Aa(J.fb())};k.Aa=function(a){va(this.Z);this.Z=i;if(a===J.Ib.Ka)this.Z=ua(this.Tb,1E3)};k.Pc=function(){if(this.ib===g||this.ib())this.M++,this.ea++,this.Fa&&this.Fa()};k.terminate=function(){va(this.Z);this.Z=i;F.U(this.zb)};k.$=function(){this.terminate();this.Fa=this.ib=g};function K(a){H.call(this);this.O=a;this.ma=a.getAttribute("data-cb-ad-id")||a.id||"";this.Cb=s(this.Cb,this);this.Jb=0;this.gb=1;this.ab=Bb;var b=this;this.ba=new Ab(function(){Cb(b);return ub(b.P)},s(this.Fa,this));Db&&this.La();this.q()}var Db;m(K,H);
K.prototype.q=function(){K.Q.q.call(this);this.Jb++;this.F={};this.F.campaignId="";this.F.creativeId="";this.F.placementId="";this.F.siteId="";this.F.server_height="";this.F.server_width="";this.F.lineId="";this.P=this.O;this.Oa=this.pb=this.lb=this.rb=this.eb=j;this.da={};this.da.iab=j;this.da.frame=j;this.da.roadblock=j;Cb(this);this.bb=Eb;this.Lb=this.jc=j;this.Eb={};this.ba.q();this.ic=j;this.Ja=0;this.ua=i;this.hd=F.D("s",this.Sb,this);this.Sb(J.fb())};
K.prototype.La=function(){var a=this;this.na=new Db(this.ma,function(){return{adContainer:a.O,creativeContainer:a.P,viewableIntervals:a.Ja,creativeScenarios:a.da,adPingData:Fb(a)}})};var Bb=0,Eb=0;K.prototype.Sb=function(a){if(this.ua!==i)va(this.ua),this.ua=i;this.Ja=0;if(a===J.Ib.Ka)this.ua=ua(this.Cb,100)};K.prototype.Cb=function(){if(ub(this.P)){if(this.Ja++,this.Ja>=10)this.ic=h,Gb(this),F.J("p")}else this.Ja=0;this.na&&this.na.update()};function Gb(a){F.U(a.hd);va(a.ua);a.ua=i}
K.prototype.Fa=function(){F.J("e",this);this.jc&&F.J("z",this.Eb,1);this.na&&this.na.update()};var Hb={300:{250:1,600:1,1050:1},180:{150:1},160:{600:1},728:{90:1},970:{90:1,66:1,250:1,415:1,550:1},120:{60:1},88:{31:1},62:{88:1},196:{31:1}};
function Cb(a){var b=l._sf_async_config;if(b&&(b=b.creativeDetection,b===j||B(b)&&b!=="iab"))return;var c=tb(a.O);if(a.P!==a.O)if(b=tb(a.P),b>c||b===0)a.P=a.O;else if(b>0)return;p(["iframe","embed","object","img","div"],function(b){p(a.O.getElementsByTagName(b),function(b){var d=rb(b);if(!(d.height*d.width>c)&&Hb[d.width]&&Hb[d.width][d.height])return a.P=b,a.da.iab=h,j});return a.P===a.O})}
function Ib(a,b,c){if(b.exclude)a.eb=h;if(b.noRefresh)a.rb=h;var d=b.roadblock;a.Oa=d==="master";a.pb=a.Oa||d==="companion";a.da.roadblock=d||j;a.Lb=!!b.dynamicLogic;a.F=b;a.lb=!!c;if(a.lb){var d=h,e=l._sf_async_config;if(e&&(e=e.creativeDetection,e===j||B(e)&&e!=="iframe"))d=j;if(d&&tb(c)>0)a.P=c,a.da.frame=h}F.J("p");if(b=b.vizu)a.jc=h,a.Eb=qa(b),F.J("z",a.Eb,a.ba.M)}function L(a,b){return a.F&&t(a.F[b])?a.F[b]:""}
var O="engagedSeconds",Jb={od:"id",nd:O,kd:"campaignId",ld:"creativeId",pd:"placementId",md:"element"};function Kb(a){var b={};b.id=a.ma;b[O]=a.ba.M;b.campaignId=L(a,"campaignId");b.creativeId=L(a,"creativeId");b.placementId=L(a,"placementId");return b}
function Fb(a){var b={};b.an=a.ma;b.aE=a.ba.M;if(a.P){var c=wb(a.P,g,h);b.ax=c.x;b.ay=c.y;c=rb(a.P);b.aw=c.width;b.ah=c.height}b.aV=a.ic;b.ao=a.Jb;b.ac=L(a,"campaignId");b.av=L(a,"creativeId");b.aP=L(a,"placementId");b.aS=L(a,"siteId");b.aW=L(a,"server_width");b.aH=L(a,"server_height");b.aL=L(a,"lineId");b.exclude=a.eb;b.am=a.ab;b.aR=a.bb;return b}
function Lb(a){var b=encodeURIComponent(a.an),c=a.aE,d=a.ax,e=a.ay,f=a.aw,n=a.ah,o=encodeURIComponent(a.av||""),q=encodeURIComponent(a.ac||""),w=encodeURIComponent(a.aP||""),z=encodeURIComponent(a.aS||""),M=encodeURIComponent(a.aH||""),N=encodeURIComponent(a.aW||""),Z=encodeURIComponent(a.aL||""),W=a.ao,A=a.aR,x=a.am,Gc=a.aV?"1":"0";a.exclude&&(q="");return b+"="+[c,d,e,f,n,q,o,W+"."+A,Gc,w,z,M,N,Z,x].join("::")}
K.prototype.Ia=function(){if(!this.lb){var a=this.O,b={};b.campaignId=E("data-cb-campaign-id",a)||"";b.creativeId=E("data-cb-creative-id",a)||"";b.placementId=E("data-cb-placement-id",a)||"";b.siteId=E("data-cb-site-id",a)||"";b.server_height=E("data-cb-creative-height",a)||"";b.server_width=E("data-cb-creative-width",a)||"";b.lineId=E("data-cb-line-id",a)||"";b.roadblock=E("data-cb-roadblock",a)||"";b.dynamicLogic=E("data-cb-dynamic-logic-id",a)||"";if(E("data-cb-exclude",a))this.eb=h;if(E("data-cb-no-refresh",
a))this.rb=h;ma(b,this.F)||Ib(this,b)}};K.prototype.refresh=function(){Gb(this);this.ba.terminate();this.q()};K.prototype.$=function(){K.Q.$.call(this);Gb(this);this.ba.$();this.F=this.P=this.O=this.ba=i;this.na&&this.na.dispose()};var P={};P.G=function(a){var b=l._sf_async_config;if(!a&&b&&b.noCookies)return i;if(P.G.cb!==g)return P.G.cb;var a=r()+"",c,d;try{if((d=l.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return P.G.cb=d}catch(e){}return P.G.cb=i};P.B=function(a){var b=P.G();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&r()>c)?(P.remove(a),""):b.getItem(a)||""};
P.create=function(a,b,c){var d=P.G();if(d){var e=new Date;e.setTime(r()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};P.remove=function(a){var b=P.G();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Mb(){this.xc=l._sf_async_config||{};this.kb=s(this.kb,this);this.jb=s(this.jb,this);this.Sa=Nb;this.Pb=[]}(function(a){a.Rb=function(){return a.Qc||(a.Qc=new a)}})(Mb);var Ob=["placementId","id",O],Nb=0;function Pb(){var a=Mb.Rb(),b=P.B("_cba_rc");b?Qb(a,b):Aa("//adsapi.chartbeat.com/advertising/adrefresh/config/cache/v1/?host="+encodeURIComponent("ads."+a.xc.domainAd),a.kb,a.jb)}
function Qb(a,b){if(b){var c=b.split("::");if(c[0].length===1&&(a.Sa=parseInt(c.splice(0,1),10),isNaN(a.Sa)))a.Sa=Nb;a.Pb=na(c,function(a){var b={};p(a.split("<>"),function(a,c){if(a){var d=Ob[c];b[d]=d===O?parseInt(a,10):a}});return b})}F.J("g")}Mb.prototype.kb=function(a){a=a.responseText;Qb(this,a);P.create("_cba_rc",a,43200)};Mb.prototype.jb=function(){F.J("g")};var Q={};Q.uc=function(){try{Q.create("_cb_test","1",1);var a=Q.B("_cb_test");Q.remove("_cb_test");return a==="1"}catch(b){return j}};Q.B=function(a){a+="=";var b="";p(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
Q.create=function(a,b,c){var d=l._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(r()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};Q.remove=function(a){return Q.B(a)?Q.create(a,"",-86400):""};function Rb(a){this.Ra=a||"";this.wc=P.G()!==i||Q.uc();this.Ab=j;Sb(this)}k=Rb.prototype;k.isSupported=function(){return this.wc};
function Sb(a){if(!Q.B("_cb_ls")){var b=P.G()!==i,c=Q.B("_SUPERFLY_nosample");c&&p(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_nosample",c,600,h)});var d=Q.B("_chartbeat3");d&&(a.create("_v__chartbeat3",d,2592E3,h),Q.remove("_chartbeat3"));b&&((b=Q.B("_chartbeat2"))&&a.create("_chartbeat2",b,94608E3,h),(b=Q.B("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,94608E3,h),(b=Q.B("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));Q.create("_cb_ls","1",2592E3)}}
function Tb(a){var b=a.Ab;a.Ab=j;return b}k.create=function(a,b,c,d){a=d?a:this.Ra+a;(P.G()?P:Q).create(a,b,c);P.G()&&Q.create(a,b,c)};k.update=function(a,b,c,d,e,f,n){a=d?a:this.Ra+a;e=B(e)?e:"::";d=(d=this.B(a,h))?d.split(e):[];if(n&&d.length){var o=n(b),q=oa(d,function(a){return n(a)===o});q!==-1&&d.splice(q,1)}y(f)&&d.length>=f&&d.splice(0,d.length-f+1);d.push(b);this.create(a,d.join(e),c,h)};
k.B=function(a,b){var a=b?a:this.Ra+a,c=(P.G()?P:Q).B(a);if(!c&&P.G()&&(c=Q.B(a))&&Q.B("_cb_ls")){this.Ab=h;var d;switch(a){case "_SUPERFLY_nosample":d=600;break;case "_chartbeat4":d=3600;break;case "_cb_cp":d=3600;break;case "_chartbeat3":d=2592E3;break;default:d=94608E3}P.create(a,c,d)}return c};k.remove=function(a,b){a=b?a:this.Ra+a;(P.G()?P:Q).remove(a);P.G()&&Q.remove(a)};function Ub(a){var b=i;if(a&&(b=Vb()))return b;var c=l.location,b=R(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function Vb(){var a=i;p(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=kb(b.href),a=R(b.pathname)+b.search+b.hash,j});return a}
for(var Wb={},Xb=0;Xb<81;Xb++)Wb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Xb)]=h;function Yb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Wb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function R(a){if(!B(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Yb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function Zb(a,b){Ab.call(this,a,b)}m(Zb,Ab);Zb.prototype.q=function(){this.ea=this.M=0;this.Z=i;this.zb=F.D("x",this.Aa,this);this.Aa(J.Ec())};Zb.prototype.Aa=function(a){va(this.Z);this.Z=i;if(a===J.oc.Ka)this.Z=ua(this.Tb,1E3)};function S(){H.call(this);this.oa=[];this.H=new Rb(this.hc);this.N=new Ab;this.la=new Zb;this.ub=s(this.Ga,this);v(l,"unload",this.ub);fb(s(this.q,this))}m(S,H);k=S.prototype;k.Va=h;
k.q=function(){S.Q.q.call(this);this.Ma=this.fa=0;this.ia=r();this.ta=ga($b(this));this.sa=h;this.qb=72E5;if(this.Va){var a=+this.k.sessionLength;if(!isNaN(a))this.qb=a*6E4}a=T(ac);if(!a){var a=[],b=this.H.B("_chartbeat2",h);b.length>0&&(a=b.split("."));a.length>4&&(a=[]);var b=r(),c=b-+(a[1]||0),d=b-+(a[2]||0),e=bc,c=a[0]&&c>18E5&&d<2592E6?0:1;U()[e]=c;c="1";d=a&&+a[2];e=a&&a[3];if(a&&d&&e)if(c=Math.abs((ka(b)-ka(d))/864E5)){c=Math.min(c,16)-1;for(d="";c--;)d+=0;c=(e+d+"1").slice(-16)}else c=e;e=
c;a[0]||(a[0]=this.k.utoken||ga($b(this),3),a[1]=b);a[2]=b;a[3]=e;this.k.utoken=this.ka;this.H.create("_chartbeat2",a.join("."),94608E3,h);b=ac;U()[b]=a}this.sd=a.join(".");var f;e=+a[1];c=+a[2];if((b=a[3])&&e&&c)f=(Math.min((Math.abs((ka(c)-ka(e))/864E5)||0)+1,16,b.length)-1).toString(16),f+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.Qb=f;this.Sc=T(bc,1);this.ka=a[0];this.N.q();this.la.q();J.q();G.q();Ua||(Va=db(),Wa&&l.document.addEventListener&&l.document.addEventListener(Wa,eb,j),cb("focus",
"onfocusin",ab),cb("blur","onfocusout",bb),Va&&ab(),Ua=h);this.Da=0;this.qc=F.D(Ta,this.tb,this)};function cc(a){if(!a.H.B("_SUPERFLY_nosample")&&!Za)a.Rc?a.Wa():(a.Rc=h,!l._sf_async_config&&!l._cbq?(a.Qa=s(a.Wa,a),v(l,"load",a.Qa)):a.Wa())}k.Wa=function(){var a=l._sf_startpt,b=l._sf_endpt;if(y(a))this.vb=y(b)?b-a:r()-a;G.q();a=s(this.Ea,this);this.Ub=ua(a,15E3);this.Ea()};
k.Ea=function(){var a=this.N.ea,a=this.k.reading&&+this.k.reading||a>0;if(this.Ma<this.fa&&!a)this.Ma++;else{var b;if(sa===g)b=l.navigator.userAgent,sa=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=sa;b&&!a?this.Ma++:(a?this.fa=0:dc(this),this.Ma=0,this.oa.push(0),this.oa.length>18&&this.oa.shift(),this.Va&&r()-this.ia>=this.qb?this.terminate():this.aa())}};
function ec(a){var b={};b.g=a.k.uid;b.g0=pb(a.k,"sections");b.g1=pb(a.k,"authors");b.g2=pb(a.k,"zone");b.g3=pb(a.k,"sponsorName");b.g4=pb(a.k,"type");!a.k.noCookies&&a.H.isSupported()?b.n=a.Sc:b.nc=1;b.c=Math.round((r()-a.ia)/600)/100;b.E=a.N.M;b.EE=a.la.M;var c=fc(a);a.Da=Math.max(a.Da,c);b.x=c;b.m=a.Da;b.y=Ia("Height");b.o=Ia("Width");b.w=Ha();b.b=a.vb?a.vb:"";if(a.Qb)b.f=a.Qb;b[""]=qb(a.k);b.t=a.ta;b.V=70;b.tz=(new Date).getTimezoneOffset();b.sn=a.wb;return b}
k.cc=function(){this.oa.push(1);var a=0;p(this.oa,function(b){a+=b});a<3?(this.sa=h,dc(this)):(this.terminate(),this.H.create("_SUPERFLY_nosample","1",600))};k.Ga=function(){};k.tb=function(){var a=fc(this);this.Da=Math.max(this.Da,a)};function fc(a){return Fa("Y","Top",!!a.k.scrollElement)}function dc(a){var b=a.fa,b=b?Math.min(b*2,16):1;a.fa=b}k.wa=function(){this.Ga();this.terminate()};k.yb=function(){this.q();cc(this)};
function gc(a){if(a.k.virtualReferrer)return h;a=(document.referrer||"").indexOf("://"+l.location.hostname+"/");return a!=-1&&a<9}function hc(a){a=a.k.virtualReferrer;if(!a&&(a=document.referrer||"")){var b=kb(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=R(b.pathname),a=lb(b)}return encodeURIComponent(a)}function ic(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function $b(a){a=[hc(a),Ia("Width"),Ia("Height")];return ia(a)}
function jc(a){var b=[],c=a.H.B("_chartbeat4");c&&(p(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.H.remove("_chartbeat4"));return b}k.terminate=function(){this.N.terminate();this.la.terminate();F.U(this.qc);this.Qa!==g&&ja("load",this.Qa);va(this.Ub);var a=ac;U()[a]=g;a=bc;U()[a]=g};k.$=function(){this.terminate();ja("unload",this.ub);this.ub=this.Qa=this.H=this.oa=this.k=i;this.N.$();this.N=i;this.la.$();this.la=i;S.Q.$.call(this)};var ac="d",bc="n";function T(a,b){var c=U();return t(b)&&!t(c[a])?b:c[a]}function U(){t(l._cb_shared)||(l._cb_shared={});return l._cb_shared};function V(){this.S=[];this.Ta=[];"postMessage"in window&&v(window,"message",s(this.Nc,this));this.hc="_p_";this.Va=this.Vb=j;v(l,"beforeunload",s(this.Vc,this));if(mb()>0){var a=s(this.La,this);U().a=a;var a="ad_debug",b="//static.chartbeat.com";Oa()&&(b="//static2.chartbeat.com");b=[b,"js"];Oa()&&(a+="dev");b.push("chartbeat_"+a+".js");Na(b.join("/"))}this.Ua=[];S.call(this)}m(V,S);k=V.prototype;
k.q=function(){V.Q.q.call(this);var a=l.location;I(this.k,"pingServer","ping.chartbeat.net");I(this.k,"title",document.title);I(this.k,"domain",a.hostname);this.k.domain=u(this.k.domain);I(this.k,"domainAd",this.k.domain);I(this.k,"path",Ub(!!this.k.useCanonical));I(this.k,"engaged",j);this.ca=this.k.adIdentifier||"data-cb-ad-id";this.pa=this.Wb=0;this.Dc=function(){var a=r()-this.Wb;if(a<500){this.pa&&D(this.pa);var b=s(this.aa,this);this.pa=wa(b,500-a)}else this.sa||this.aa()};this.Cc=F.D("p",this.Dc,
this);this.xa={};this.Ca=0;if((a=this.k.engagedAdFilters)&&a.length){var b=this;p(a,function(a){b.va(a)})}this.Ia();this.Xc=F.D("g",this.Lc,this);Pb();this.jd=F.D("z",this.ed,this);if(this.k.krux&&!this.Vb)ea("http://beacon.krzd.net/usermatch.gif?partner=chartbeat&partner_uid="+this.ka),this.Vb=h;this.Ta=[]};k.Lc=function(){var a=Mb.Rb(),b=a.Sa;if(b===1||b===2){this.Mb=F.D("e",this.yc,this);p(a.Pb,s(this.va,this));try{l.googletag.pubads().addEventListener("slotRenderEnded",s(this.Ic,this))}catch(c){}}};
k.Ic=function(a){if(this.Ua.length)try{p(this.Ua,s(function(b,d){var e=b.hb;a.slot===e&&(e.setTargeting("_cbr",kc),b.gb>=100||(b.gb+=1),this.Ua.splice(d,1))},this))}catch(b){}};k.La=function(a,b){var c=xa(F,Sa),d=xa(J,zb),e=s(function(){return{engagedAdFilters:this.xa,maxEngagedAdSpecificity:this.Ca}},this);a.injectDependencies(c,d,e);b.injectDependencies(c);this.Kb=new a;Db=b;p(this.S,function(a){a.La()})};k.Vc=function(){lc(this);this.aa(h)};
k.Ga=function(){this.H.update("_chartbeat4",["t="+this.ta,"E="+this.N.M,"ad="+la(mc(this,h)),"x="+fc(this),"c="+Math.round((r()-this.ia)/600)/100,"y="+Ia("Height"),"w="+Ha()].join("&"),3600,g,g,1)};function nc(a){return encodeURIComponent("ads."+a.k.domainAd)}function mc(a,b){var c=[];p(a.S,function(a){a=Fb(a);(!b||!(a.aw<=1&&a.ah<=1))&&c.push(Lb(a))});return c.concat(a.Ta).join("&")}var oc="h,p,u,d,g,g0,g1,g2,g3,g4,n,nc,f,c,x,m,y,o,w,j,E,v,r,vp,b,t,V,i,tz,l,,ad,z,zz,sn".split(",");k=V.prototype;
k.aa=function(a){this.wb++;var b=ec(this),c=l.location;b.h=nc(this);b.p=encodeURIComponent(this.k.path);b.u=this.ka;b.d=la(u(c.hostname));gc(this)?b.v=hc(this):b.r=hc(this);b.ad=la(mc(this));this.Wb=r();this.pa&&D(this.pa);Ub(!!this.k.useCanonical);if(this.sa)this.sa=j,b.i=ic(this);this.k.virtualReferrer&&(b.vp=1);var c=this.k.pingServer,d=0;a?b.zz=1:(b.z=jc(this),d=Math.round((this.fa+2)*15E3/1E3));b.j=d;b.l=Tb(this.H)?1:"";this.N.ea=0;this.Ha("https://"+c+"/ping/ad?"+jb(b,oc))};
function pc(a){var b=Da(a.ca,"div");p(b,function(b){if(!qc(a,b)){var d=new K(b);a.S.push(d);d.Ia();if(b=E("data-cb-engaged-seconds",b))d=Kb(d),d[O]=parseInt(b,10),a.va(d)}})}function qc(a,b){var c;p(a.S,function(a){if(a.ma===b||a.O===b)return c=a,j});return c}k.Ia=function(){var a=T("c");pc(this);var b=this;p(this.S,function(c){c.Ia();var d=c.ma;if(a&&a[d]){var e=-1;p(a[d],function(a,d){if(a.e===c.O)return a.c(b.ta,nc(b)),e=d,j});e>-1&&a[d].splice(e,1)}})};k.tb=function(){V.Q.tb.call(this);pc(this)};
k.Nc=function(a){this.Xb(B(a.data)?qa(a.data):{},a.source)};
k.Xb=function(a,b){if(a.cbType!=="campaignMessage")return j;var c=b;if(c.parent!=window){for(var d=0;c.parent!=window&&d<10;)c=c.parent,d++;if(d>=10)return j}pc(this);var d=document.getElementsByTagName("iframe"),e=g;p(d,function(a){if(a.contentWindow===c)return e=a,j});if(!e)return j;var f=e.getAttribute(this.ca),n;if(f===i){n=Ea(e,this.ca);if(!n)return j;f=n.getAttribute(this.ca)}else n=e;var o=g;p(this.S,function(a){if(f===a.ma&&n===a.O)return o=a,j});if(o===g)return j;Ib(o,a,e);if(d=a[O]){var q=
Kb(o);q[O]=parseInt(d,10);this.va(q)}d=["cbdata::ack",this.ta,nc(this)].join("::");"postMessage"in b&&b.postMessage(d,"*");return d};k.va=function(a){if(a&&y(a[O])&&!isNaN(a[O])){var b={};p(Jb,function(c){if(B(a[c])||c===O)b[c]=a[c]});var c=ya(b).length;this.Ca=Math.max(this.Ca,c);this.xa[c]=this.xa[c]||[];var c=this.xa[c],d=j;p(c,function(a){var c=h;p(a,function(a,d){if(d!==O)return c=b[d]===a});(d=c)&&(a[O]=b[O]);return!d});d||c.unshift(b);this.Kb&&this.Kb.update()}};
k.Yc=function(a,b){if(!a)return j;var c=l.document.getElementById(b);if(!c)return j;var d;c.getAttribute(this.ca)&&(d=qc(this,c));var e=this;if(!d){var f=Da(this.ca,"div",c);p(f,function(a){if(d=qc(e,a))return j})}d||(c=Ea(c,this.ca))&&(d=qc(this,c));if(!d)return j;d.hb=a;return h};
k.yc=function(a){if(a&&this.Ca!==0){var b=a.hb,c=this.k.engagedAdCallback;b&&!c&&(c=ta);if(c)for(var d=this,e=Kb(a),f=e[O],n=this.Ca,o=j;n>0&&!o;)p(this.xa[n]||[],function(n){o=h;p(n,function(a,b){if(b!==O)return o=a===e[b]});if(o){n=n[O];if(n===-1)return j;if(n===f)e.element=a.O,c(e,f),b&&a.rb==j&&(a.pb?rc(d,a):sc(d,a));return j}}),n--}};k.Wc=function(a){if(a&&(a=qc(this,a))){a.bb=1;var b=Fb(a);this.Ta.push(Lb(b));a.refresh();a.ab=1}};var kc="0";
function sc(a,b){b.bb=2;var c=Fb(b);a.Ta.push(Lb(c));b.refresh();c=b.hb;try{c.setTargeting("_cbr",b.gb),a.Ua.push(c),l.googletag.pubads().refresh([c]),b.ab=2}catch(d){}}
V.prototype.ed=function(a,b){for(var c=qa(this.H.B("_chartbeat7")),d=parseInt(c[a.vzcid],10)||0,e={1:h,5:h,15:h,30:h,60:h,100:h};b--;)if(d++,e[d+""]){var f=a,n=d+"second"+(d!==1?"s":""),o=ga(fa());ea("http://ohlone.vizu.com/a.gif?vzcid="+f.vzcid+"&vzadid="+n+"&vzsid="+f.vzsid+"&ord="+o)}c[a.vzcid]=d;this.H.create("_chartbeat7",pa(c),94608E3)};function tc(a){var b=j;p(a.S,function(a){if(a.Oa)return b=h,j});return b}
function lc(a){p(a.S,function(a){a.Lb&&ea("//secure.insightexpressai.com/adServer/cb.gif?bannerid="+a.F.dynamicLogic+"&siteID="+a.F.siteId+"&placementID="+a.F.placementId+"&creativeID="+a.F.creativeId+"&inViewTime="+a.ba.M+"&vendor=cb")})}function rc(a,b){(b.Oa||!tc(a))&&p(a.S,function(b){b.pb&&sc(a,b)})}V.prototype.terminate=function(){F.U(this.Cc);F.U(this.Xc);F.U(this.jd);this.Mb&&F.U(this.Mb);p(this.S,function(a){a.$()});this.S=[];D(this.pa);V.Q.terminate.call(this)};if(!l.pSUPERFLY_pub){var X=new V,uc={addEngagedAdFilter:s(X.va,X),refreshAd:s(X.Wc,X),updateCampaignData:s(X.Ia,X),registerGptSlot:s(X.Yc,X)};uc.evps=s(X.wa,X);uc.svps=s(X.yb,X);"postMessage"in window!==h&&(uc.loadCampaign=s(X.Xb,X));l.pSUPERFLY_pub=uc;cc(X)};function vc(a){for(var b=T("m")||[];b.length;)a(b.shift());a={push:a};U().m=a};function wc(){var a=l.location.href,a=a.replace(/-{2,}/g,"-"),a=kb(a);a.pathname=R(a.pathname);return a}
function xc(a){var b=Q.B("_chartbeat6");if(!b)return i;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var e,f=wc(),n=lb(f);p(b,function(a,b){var f=a.split(","),o=ra(n,decodeURIComponent(f[0]));if(o===0)return c=f,d=b,j;if(e===g||o<e)e=o,c=f,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+yc(a);document.cookie=a;var a=[],b=c[0],f=c[1],o=c[2];c.splice(0,3);for(var q=c.length/2,w=0;w<q;w++)a.push({qd:b,origin:f,ra:o,zc:c[w*2],fd:c[w*2+1]});return a}
function yc(a){var b="",c;if(!C(a))return b;a.$b&&(c=new Date,c.setTime(c.getTime()+a.$b),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function zc(a){var b=a.topStorageDomain,a=a.domain,c=l.location.hostname;return b?b:Ac(c,a)?a:c.replace(/^www\./,"")}function Ac(a,b){if(a===b)return h;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return j;if(c.pop()!==d.pop())return j}return h}
function Bc(a,b,c,d){this.Bc=a;this.Ac=b;this.gd=c;this.ra=d};function Cc(a,b){for(var c=b||document.documentElement,d=[],e=i,f=a,n,o,q,w,z,M;f&&f!==c;){n=f.nodeName.toLowerCase();e=f;o=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){q=f.children;w=0;for(z=0,M=q.length;z<M;z++){if(e===q[z]){n+="["+(1+z-w)+"]";break}q[z].nodeName!==o&&w++}}d.unshift(n)}return d.join("/")};function Dc(){this.hc="_t_";S.call(this)}m(Dc,S);k=Dc.prototype;
k.q=function(){Dc.Q.q.call(this);ob(this.k);var a=l.location;I(this.k,"mabServer","mabping.chartbeat.net");I(this.k,"title",document.title);I(this.k,"domain",a.hostname);I(this.k,"path",Ub(!!this.k.useCanonical));this.Ba=u(a.hostname);this.k.domain=u(this.k.domain);this.cd=zc(this.k);this.ya=this.Na=j;this.Ob=[];var b=this,a=xc({domain:"."+this.cd,$b:6E4,path:"/"});if(a!==i)this.Na=h,p(a,function(a){b.Ob.push(new Bc(a.origin,a.zc,a.fd,a.ra))});this.bc=0;this.Xa=i;vc(s(this.Oc,this))};
k.aa=function(){var a=this.N.M,b=Ec(this),c,d=this;this.Na&&p(this.Ob,function(e){c=b+"&x="+e.Ac+"&v="+e.gd+"&ml="+e.ra+"&xo="+e.Bc+"&e="+a;d.Ha(c)});!this.ya&&this.Xa&&Fc(this,this.Xa);this.ya=h};k.Wa=function(){var a=l._sf_startpt,b=l._sf_endpt;if(y(a))this.vb=y(b)?b-a:r()-a;G.q();if(this.Na)a=s(this.Ea,this),this.Ub=ua(a,500);this.Ea()};k.Ea=function(){var a,b;this.ya?(a=this.N.M,b=this.bc*15,a-b>=15&&(this.aa(),this.bc+=1),a>=45&&this.terminate()):this.aa()};
function Ec(a){var b=a.k;return(l.location.protocol||"http:")+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.Ba)+"&u="+a.ka+"&c="+Math.round((r()-a.ia)/600)/100}k.Ga=function(){};k.bd=function(a){var b=a.d,c=i;b!==i&&(c={fc:b.s,ra:b.g,Zb:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.ya?Fc(this,a):this.Xa=a};
function Fc(a,b){var c=Ec(a),d=b.status,e=b.data;if(d=="s"&&e!==i){var f=s(a.Ha,a);C(e.fc)&&p(e.fc,function(a,b){f(c+"&x="+b+"&v="+a+"&ml="+e.ra+"&e=-1")});Object.prototype.toString.call(e.Zb)==="[object Array]"&&p(e.Zb,function(a){f(c+"&me=3&ml="+e.ra+"&x="+a)})}else d=="e"&&a.Ha(c+"&me="+b.code)}k.Oc=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],e=a.shift();e==="t"?this.bd.apply(this,a):e==="v"&&this.$c.apply(this,a)}};k.wa=function(){U().m=[];t(this.Db)&&this.Db();Dc.Q.wa.call(this)};
k.$c=function(a){this.Db=a};k.terminate=function(){this.Db=this.rd=g;this.Xa=i;this.ya=this.Na=g;Dc.Q.terminate.call(this)};if(!l.pSUPERFLY_mab){var Hc=new Dc,Ic={};Ic.evps=s(Hc.wa,Hc);Ic.svps=s(Hc.yb,Hc);l.pSUPERFLY_mab=Ic;cc(Hc)};var Jc,Kc,Lc;function Mc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0&&(a=a.substr(16),Nc(),a!=="NONE"))){var a=a.indexOf("HUD2.")===0?a.substr(5):"OLD",b="https://static.chartbeat.com/js/inpage.js";a!=="OLD"&&(b="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+a+".js");Na(b)}}function Nc(){D(Kc);Kc=g;ja("message",Mc);Lc&&Lc.parentNode&&Lc.parentNode.removeChild(Lc);Lc=g};function Oc(){var a=l._sf_async_config&&l._sf_async_config.domain;if(a&&!Jc){Jc=h;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);v(l,"message",Mc);Kc=wa(Nc,1E4);var b=t(g)?g:{};b.src=a;a=Ma("iframe",b);a.style.display="none";t(g)?g.appendChild(a):document.body&&document.body.appendChild(a);Lc=a}}
function Pc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=P.G(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Oc(),ja("message",Pc))}};function Y(){"postMessage"in window&&v(l,"message",s(this.Mc,this));S.call(this);nb("_cbq",s(this.dc,this))}m(Y,S);
Y.prototype.q=function(){Y.Q.q.call(this);var a=this.ka;U().u=a;a=this.ta;U().t=a;this.$a=i;ob(this.k);a=l.location;I(this.k,"pingServer","ping.chartbeat.net");I(this.k,"title",document.title);I(this.k,"domain",a.hostname);this.k.path=this.k.path?R(this.k.path):Ub(!!this.k.useCanonical);this.Ba=u(a.hostname);this.k.domain=u(this.k.domain);this.sc=F.D("c",this.Tc,this);this.tc=F.D("r",this.Uc,this);this.qa=i};Y.prototype.pc=function(a){this.$a=a};
Y.prototype.Ga=function(){this.H.update("_chartbeat4",["t="+this.ta,"E="+this.N.M,"EE="+this.la.M,"x="+fc(this),"c="+Math.round((r()-this.ia)/600)/100,"y="+Ia("Height"),"w="+Ha()].join("&"),3600,g,g,1)};var Qc="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR,EE".split(",");k=Y.prototype;
k.aa=function(a){this.wb++;var b=ec(this),c=this.N.ea;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.ka;b.d=encodeURIComponent(this.Ba);b.j=Math.round((this.fa+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var d=b.c*6E4+this.ia;b.eD=G.za("mousedown",d);b.eM=G.za("mousemove",d);b.eK=G.za("keydown",d);b.eR=G.za("resize",d);b.eS=G.za("scroll",d);G.Zc();G.rc()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=gc(this);if(this.sa){this.sa=j;if(c)this.qa=Rc(this);
b.i=ic(this);d=this.k.hudTrackable;d!==g&&(b.L=d?"1":"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.qa){if(b.v=encodeURIComponent(this.qa.path),b.K=Sc(this.qa),this.qa.sb>1)b.l1=this.qa.sb}else b.v=hc(this);this.k.virtualReferrer&&(b.vp=1)}else b.r=hc(this);c=Ca(b.v);U().v=c;c=Ca(b.r);U().r=c;b.A=this.$a?this.$a:"";b._c=hb("utm_campaign",this.k.campaignTag);b._m=hb("utm_medium",this.k.mediumTag);b.z=jc(this);b.C=this.k.mobileApp?1:"";b.KK=a?Sc(a):"";b.l=Tb(this.H)?1:"";this.N.ea=
0;this.Ha((l.location.protocol||"http:")+"//"+this.k.pingServer+"/ping?"+jb(b,Qc))};
k.Mc=function(a){var b=this.k;if(a.origin==="http://"+(b.playerdomain||this.Ba)){var c=a.data;if(B(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.dc(a));else if(c=="cbdata?"){var c="&u="+T("u"),d="&t="+T("t"),e="&v="+T("v"),f="&r="+T("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+ic(this)+"&referrer="+hc(this)+"&internal="+(gc(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.Ba)+
c+d+e+f+"&utoken="+this.ka;a.source.postMessage(b,"*")}}};k.dc=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.fa=0};function Tc(a){a=a.replace(/-{2,}/g,"-");a=kb(a);a.pathname=R(a.pathname);return a}k.Tc=function(a){Uc(this,a,"c")};k.Uc=function(a){Uc(this,a,"r")};
function Uc(a,b,c){if(a.Va&&r()-a.ia>=a.qb)a.terminate();else{var d=b.href||"",d=Tc(d);if(!(d.hostname!==l.location.hostname||d.protocol.indexOf("http")!==0)){var d=lb(d),e=Ja(b,function(a){return a.id}),f=Cc(b,e);e&&(f&&(f="/"+f),f="*[@id='"+e.id+"']"+f);e=ga(f);b=wb(b,g,h);c={left:b.x,top:b.y,path:a.k.path,href:d,Gb:e,Fb:f,xb:c,sb:0};a.aa(c);a.H.update("_chartbeat5",Vc(c),60,j,g,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function Sc(a){return[a.left,a.top,a.Gb,encodeURIComponent(a.Fb),a.xb,encodeURIComponent(a.href)].join("::")}function Vc(a){var b=encodeURIComponent(a.Fb),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.Gb,b,a.xb].join(",")}
function Rc(a){var b=a.H.B("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,d,e;if(b===1)d=c[0].split(","),e=0;else{var f,n=Tc(l.location.href),o=lb(n);p(c,function(a,b){var c=a.split(","),n=ra(o,decodeURIComponent(c[3]));if(n===0)return d=c,e=b,j;if(f===g||n<f)f=n,d=c,e=b})}c.splice(e,1);a.H.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),href:decodeURIComponent(d[3]),Gb:d[4]||
"",Fb:a,xb:d.length>6?d[6]:"c",sb:b}}k.terminate=function(){F.U(this.sc);F.U(this.tc);Y.Q.terminate.call(this)};if(!l.pSUPERFLY){var Wc=new Y,Xc={};l.pSUPERFLY=Xc;var Yc=l.pSUPERFLY_mab,$=l.pSUPERFLY_pub,Zc=[];Yc&&Zc.push(Yc);if($)Zc.push($),$.addEngagedAdFilter&&(Xc.addEngagedAdFilter=$.addEngagedAdFilter),$.refreshAd&&(Xc.refreshAd=$.refreshAd),$.registerGptSlot&&(Xc.registerGptSlot=$.registerGptSlot),nb("_cba",function(a){a()});Xc.virtualPage=function(a,b){if(!Za){var c=l._sf_async_config;c.virtualReferrer=l.location.protocol+"//"+c.domain+c.path;c.path=R(a);b&&(c.title=b);Wc.wa();p(Zc,function(a){a.evps()});
Wc.yb();p(Zc,function(a){a.svps()})}};Xc.activity=s(Wc.pc,Wc);cc(Wc);var $c=P.G(h);if($c)if($c.getItem("_cb_ip")){var ad=l.location;(!/^(.+[.])?chartbeat\.com$/.test(ad.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(ad.pathname))||Oc()}else v(l,"message",Pc)};})();
